config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq web
  # from https://github.com/mperham/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      # Protect against timing attacks:
      # - See https://codahale.com/a-lesson-in-timing-attacks/
      # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])
      ) & ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])
      )
    end
  end

  mount Sidekiq::Web, at: "/sidekiq"

  # Routes

  get 'admin', to: 'admin#index', as: 'admin'
  post 'admin/login', to: 'admin#login', as: 'login'
  post 'admin/logout', to: 'admin#logout', as: 'logout'

  scope 'admin' do
    get 'cat_stats', to: 'admin#cat_stats', as: 'admin_cat_stats'
  end

  scope '(:locale)', constraints: { locale: Languages.map(&:last).map(&:to_s) } do
    root 'packages#index'

    resources :packages, only: [:index, :show] do
      post :set_cat
      get :direct_download
      get :direct_play
      get :logo, format: true, defaults: { format: Si::Package::IMAGE_EXT }
    end

    resources :authors, only: [:index, :show], constraints: { id: /.+/ }

    resources :tags, only: [:index, :show], constraints: { id: /.+/ } do
      post :toggle_cat
    end

    resources :categories, only: [:index, :show]

    namespace :profile do
      get :bookmarks
    end
  end

  # SIStorage API
  scope :sistorage do
    mount Sistorage::Api => '/api'
    mount GrapeSwaggerRails::Engine => 'swagger'
  end
end

app/views/admin/cat_stats.html.erb
<table>
  <caption>cat_stats</caption>
  <thead>
    <th>cat</th>
    <th>yes</th>
    <th>no</th>
    <th>yes / no</th>
  </thead>
<% @cats.each do |cat, dist| %>
  <tr>
    <td class="italic border border-black"><%= cat %></td>
    <td class="border border-black text-center"><%= dist[:yes] %></td>
    <td class="border border-black text-center"><%= dist[:no] %></td>
    <td class="border border-black text-center"><%= dist[:no] == 0 ? 'n/a' : (dist[:yes].to_f / dist[:no]).round(2) %></td>
  </tr>
<% end %>
</table>

app/views/admin/index.html.erb
<%= flash[:notice] %>

<% if admin? %>
  <%= button_to "Logout", logout_path, method: :post %>
<% else %>
  <%= form_with url: login_path  do |f| %>
    <%= f.label :login %>
    <%= f.text_field :login, tabindex: 1 %>

    <%= f.label :password %>
    <%= f.password_field :password, tabindex: 2 %>

    <%= submit_tag 'Login' %>
  <% end %>
<% end %>

<% if admin? %>
  <%= link_to 'Category stats', admin_cat_stats_path, class: 'font-bold' %>
<% end %>