config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq web
  # from https://github.com/mperham/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      # Protect against timing attacks:
      # - See https://codahale.com/a-lesson-in-timing-attacks/
      # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])
      ) & ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])
      )
    end
  end

  mount Sidekiq::Web, at: "/sidekiq"

  # Routes

  get 'admin', to: 'admin#index', as: 'admin'
  post 'admin/login', to: 'admin#login', as: 'login'
  post 'admin/logout', to: 'admin#logout', as: 'logout'

  scope 'admin' do
    get 'cat_stats', to: 'admin#cat_stats', as: 'admin_cat_stats'
  end

  scope '(:locale)', constraints: { locale: Languages.map(&:last).map(&:to_s) } do
    root 'packages#index'

    resources :packages, only: [:index, :show] do
      post :set_cat
      get :direct_download
      get :direct_play
      get :logo, format: true, defaults: { format: Si::Package::IMAGE_EXT }
    end

    resources :authors, only: [:index, :show], constraints: { id: /.+/ }

    resources :tags, only: [:index, :show], constraints: { id: /.+/ } do
      post :toggle_cat
    end

    resources :categories, only: [:index, :show]

    namespace :profile do
      get :bookmarks
    end
  end

  # SIStorage API
  scope :sistorage do
    mount Sistorage::Api => '/api'
    mount GrapeSwaggerRails::Engine => 'swagger'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include PackagesPagination

  helper_method :tag_id, :packages

  def index
    page = params[:page]

    @tags = Package
      .from(Package.visible.select('jsonb_array_elements_text(tags) AS tag, id'))
      .where("tag <> ''")
      .group('lower(tag)')
      .order('COUNT(tag) DESC', 'MIN(subquery.id) DESC')
      .select('MIN(tag) AS tag', 'COUNT(tag) AS count')
      .page(page).per(10)

    @page_title = t(:tags)

    if helpers.admin?
      @tags_to_cats = SibrowserConfig.instance.tags_to_cats || {}
      @cats = SibrowserConfig::CATEGORIES
    end

    set_meta_tags noindex: page.present?
  end

  def show
    return packages_pagination(packages) if request.format.turbo_stream?

    package_count = packages.total_count

    @page_title = t('title_tag', tag: tag_id)
    @page_description = t('description_tag', tag: tag_id, package_count:)

    set_meta_tags noindex: params['page'].present?

    @breadcrumbs = {
      parts: [
        [t(:tags), tags_path],
        tag_id
      ]
    }
  end

  def tag_id
    params[:id]
  end

  def packages
    Package.visible_paged(params[:page]).by_tag(tag_id)
  end

  def toggle_cat
    return head(:forbidden) unless helpers.admin?

    SibrowserConfig.instance.toggle_tag_cat(params[:tag_id], params[:cat])
    redirect_to action: :index, params: { page: params[:page] }
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<h1 class="text-2xl font-bold text-center pb-2">
  <%= t('tags') %>
</h1>

<table class="w-full">
  <thead>
    <tr class="bg-indigo-600 text-white">
      <th class="text-center py-4 px-3 <%= admin? ? 'w-96' : '' %>"><%= t('tag') %></th>
      <% if admin? %>
        <% @cats.each do |c| %>
          <th class="text-center py-4 px-3"><%= c %></th>
        <% end %>
      <% end %>
      <th class="text-center py-4 px-3"><%= t('package_count') %></th>
    </tr>
  </thead>
  <% @tags.each do |t| %>
    <tr>
      <td class="py-4 text-center">
        <%= link_to t.tag, tag_path(t.tag), class: 'font-bold' %>
      </td>
      <% if admin? %>
        <% @cats.each do |c| %>
          <td class="text-center">
            <%= button_to(
              @tags_to_cats[t.tag.downcase]&.include?(c) ? '+' : '',
              tag_toggle_cat_path(tag_id: t.tag.downcase),
              params: { cat: c, page: params[:page] },
              class: "bg-blue-300 w-10"
            ) %>
          </td>
        <% end %>
      <% end %>
      <td class="text-center">
        <%= t.count %>
      </td>
    </tr>
  <% end %>
</table>

<div class="mt-4">
  <%= paginate @tags %>
</div>

app/views/tags/show.html.erb
<h1 class="text-2xl font-bold text-center">
  <%= tag_id %>
</h1>

<h2 class="text-xl mb-2 mt-4 text-center">
  <%= t('tag_packages') %>
</h2>

<%= render PackagesPaginated::Component.new(packages:) %>