config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq web
  # from https://github.com/mperham/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      # Protect against timing attacks:
      # - See https://codahale.com/a-lesson-in-timing-attacks/
      # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])
      ) & ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])
      )
    end
  end

  mount Sidekiq::Web, at: "/sidekiq"

  # Routes

  get 'admin', to: 'admin#index', as: 'admin'
  post 'admin/login', to: 'admin#login', as: 'login'
  post 'admin/logout', to: 'admin#logout', as: 'logout'

  scope 'admin' do
    get 'cat_stats', to: 'admin#cat_stats', as: 'admin_cat_stats'
  end

  scope '(:locale)', constraints: { locale: Languages.map(&:last).map(&:to_s) } do
    root 'packages#index'

    resources :packages, only: [:index, :show] do
      post :set_cat
      get :direct_download
      get :direct_play
      get :logo, format: true, defaults: { format: Si::Package::IMAGE_EXT }
    end

    resources :authors, only: [:index, :show], constraints: { id: /.+/ }

    resources :tags, only: [:index, :show], constraints: { id: /.+/ } do
      post :toggle_cat
    end

    resources :categories, only: [:index, :show]

    namespace :profile do
      get :bookmarks
    end
  end

  # SIStorage API
  scope :sistorage do
    mount Sistorage::Api => '/api'
    mount GrapeSwaggerRails::Engine => 'swagger'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <%= display_meta_tags(
          site: t('site_name'),
          title: t('default_title'),
          description: t('default_description'),
          reverse: true,
          alternate: Languages.map do |(name, code)|
            [code, url_for(request.query_parameters.merge(locale: code == I18n.default_locale ? nil : code, only_path: false))]
          end.to_h
    )
    %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>

    <%= javascript_importmap_tags %>

    <!-- favicons from https://realfavicongenerator.net -->
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#000038">
    <meta name="theme-color" content="#ffffff">

    <% if ENV['YANDEX_VERIFICATION'] %>
      <meta name="yandex-verification" content="<%= ENV['YANDEX_VERIFICATION'] %>">
    <% end %>

    <%= yield(:head) %>
  </head>

  <body class="bg-indigo-300 text-black-20 min-h-screen flex flex-col">
    <header class="px-1 sm:px-4 flex min-h-full bg-indigo-800 text-white font-bold items-center flex-wrap pt-4">
      <div class="flex items-center pb-4 w-full lg:w-fit">
        <%= link_to root_path, class: 'mr-1 h-10 w-10 shrink-0' do %>
          <%= image_tag 'sib.png', alt: 'SIBrowser', class: 'h-10 w-10 aspect-square' %>
        <% end %>
        <ul class="flex justify-around sm:justify-start sm:space-x-4 sm:ml-4 grow inline w-full max-w-xs sm:max-w-none">
          <li class="inline"><%= link_to t(:authors), authors_path %></li>
          <li class="inline"><%= link_to t(:tags), tags_path %></li>
          <li class="inline"><%= link_to t(:categories_page_title), categories_path %></li>
          <% if admin? %>
            <li class="inline"><%= button_to "Logout", logout_path, method: :post, class: 'bg-red-700' %></li>
          <% end %>
        </ul>
        <%= render ProfileMenu::Component.new \
          class: 'ml-auto lg:hidden h-10 w-10 p-1 sm:p-0'
        %>
      </div>
      <%= form_tag(packages_path, method: :get, class: 'flex w-full grow md:grow-0 lg:w-1/3 ml-auto pb-4 flex-row') do %>
        <%= text_field_tag(:q, params[:q], class: 'p-2 text-black grow font-normal bg-white') %>
        <%= submit_tag(t('search'), name: nil, class: 'py-1 inline-block cursor-pointer bg-purple-500 hover:bg-purple-600 px-4 font-bold text-white') %>
      <% end %>
      <%= render ProfileMenu::Component.new \
        class: 'hidden lg:block mb-4 ml-4 h-10 w-10'
      %>
    </header>
    <main class="grow">
      <div class="xl:container mx-auto bg-indigo-100 p-2 pt-4 xl:my-4 md:px-4">
        <%= render Announcement::Component.new %>
        <% if @breadcrumbs %>
          <div class="pb-2">
            <%= render BreadcrumbsComponent.new(**@breadcrumbs) %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </main>
    <footer class="px-4 md:mt-4 flex flex-col justify-center items-center min-h-16 bg-indigo-800 text-white gap-4 py-4">
      <span class="block">
        <%= t('made_by') %>
        <a href="https://imustafin.tatar/<%= I18n.locale %>" class="font-bold">
          <%= t('ilgiz') %>
        </a>
      </span>
      <p class="flex flex-col md:flex-row justify-center items-center space-x-4 flex-wrap">
        <a href="https://vk.com/sibrowser" class="block font-bold"><%= t('community_vk') %></a>
        <a href="https://github.com/imustafin/sibrowser" class="block font-bold"><%= t('source_code') %></a>
        <a href="https://github.com/imustafin/sibrowser/projects/1" class="block font-bold"><%= t('roadmap') %></a>
      </p>
      <ul class="flex space-x-4">
        <% Languages.each do |(name, code)| %>
          <% if code != I18n.locale %>
            <li>
              <% if code != I18n.default_locale %>
                <%= link_to name, request.query_parameters.merge(locale: code), class: 'font-bold' %>
              <% else %>
                <%= link_to name, request.query_parameters.merge(locale: nil), class: 'font-bold' %>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </footer>
  </body>
</html>